### ISSUE TITLE
modded nbt tags

### ISSUE THREAD

**Issue by Official678** [dumptruckman/ChestRestock#18]
Hey,

is it possible to add for example by flansmod the addons on weapons?
it is possible in commandblocks with these codes:  /setblock ~ ~1 ~ chest 1 replace {Items:[{id:4290,Count:1,Slot:0,tag:{attachments:{ barrel:{id:4266},

But how do i add it to the config of chestrestock? i tried these things:

  type: FLANSMOD_M16A4
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    attachments:
      barrel:4266
      scope:4265
      grip:4264

**Comment by dumptruckman** [comment]
You cannot add these into a config manually. If you set up a chest in game with commands it SHOULD be able to restock it. No promises though. In either case, don't expect any fixes, sorry.

**Comment by Official678** [comment]
Yeah if they restock they come without addons on them but does the config support nbt tag? because then there should be a way to make it work as far as i know

**Comment by dumptruckman** [comment]
If you're using the latest version it serializes the items in the chest via Bukkit API. As far as I know, that should preserve any custom NBT tags on the item.
