### ISSUE TITLE
ChestRestock NoSuchMethod Error

### ISSUE THREAD

**Issue by mercurialmusic** [dumptruckman/ChestRestock#19]
Pastebin: https://pastebin.com/x8ppxCUT

Would very much love to see this brought back to life and happy to donate to the cause!

**Comment by DKrolls** [comment]
I get the same thing!

**Comment by dumptruckman** [comment]
Duplciate of #20.

**Comment by dumptruckman** [comment]
https://ci.onarandombox.com/job/ChestRestock/106/

**Comment by mercurialmusic** [comment]
You rock! Thanks!
