### ISSUE TITLE
[request] Setting a config per chest

### ISSUE THREAD

**Issue by FrozenBeard** [dumptruckman/ChestRestock#21]
Hello!
I just found this plugin and am using it in my survival! I have it generate items for loot hidden around my survival world.

What I would like is to have one or two special chests that broadcast messages, that have their own settings independent of those extra chests in the world. So then we could have an event that triggers at X amount of time that people all storm to an area to raid it!

**Comment by dumptruckman** [comment]
This is already possible. You need to target (look at) the chest and run the commands for the settings you want.

**Comment by FrozenBeard** [comment]
@dumptruckman sweet, whats the command?

**Comment by dumptruckman** [comment]
They are listed on dbo. https://dev.bukkit.org/projects/chestrestock

**Comment by FrozenBeard** [comment]
@dumptruckman I know, But its not documented! I would assume its /cr create <filename>, but that does not exist, create only uses the default configs, theres world specific configs.. There isnt anything listing a specific config with a command.

**Comment by dumptruckman** [comment]
It is documented right there on the dbo page. You target the chest, type `/cr create` and then you're able to use `/cr set <propertyname> <value>` on it.

**Comment by dumptruckman** [comment]
```
Type /cr set while targeting a chest you have initialized with /cr create to see a list of properties you can set for it.
Type /cr set <propertyname> to see a description of what the property does.
Type /cr set <propertyname> <value> to set a value for a property.
```

**Comment by dumptruckman** [comment]
![image](https://user-images.githubusercontent.com/669280/30677658-02a31c6a-9e5b-11e7-8066-dc80ad5207da.png)
