### ISSUE TITLE
Permission to Publish Derivative Work on Spigot?

### ISSUE THREAD

**Issue by rm2023** [dumptruckman/ChestRestock#25]
Hey there, 

I was recently commissioned to update this plugin to support post-1.13 versions of Minecraft. Once this is done, is it all right with you if I publish it so other people may use it? I will abide by the stipulations of the license and provide a link to your plugin page on Bukkit if you want that. 

Thank you, 
rm2023

**Comment by dumptruckman** [comment]
The license is here https://github.com/dumptruckman/ChestRestock/blob/master/LICENSE.txt

Personally, I'd much rather see a pull request with said updates.

**Comment by rm2023** [comment]
PR created. Ty!
